banki:
  currency:
    url: https://www.banki.ru/products/currency/cb/

spring:
  datasource:
    url: jdbc:h2:mem:exchangedb;DB_CLOSE_DELAY=-1
    username: admin
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: create

h2:
  console:
    enable: true
    path: /h2
    settings:
      trace: true
      web-allow-others: true